### ISSUE TITLE
Secure kafka support

### ISSUE THREAD

**Issue by CanerPatir** [Trendyol/go-kafka-connect-couchbase#1]
**Is your feature request related to a problem? Please describe.**
We should support secure kafka connection
**Describe the solution you'd like**
We should support secure kafka connection

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by mhmtszr** [comment]
Implemented in v0.0.10.

Example:
```
  #SSL configurations
  secureConnection: true
  #Config support env variable "$HOME/example/..."
  rootCAPath: "example/stretch-kafka/rootCA.pem"
  interCAPath: "example/stretch-kafka/interCA.pem"
  scramUsername: "username"
  scramPassword: "password"
```
