### ISSUE TITLE
chore: return error when creating new connector and producer

### ISSUE THREAD

**Issue by oguzyildirim** [Trendyol/go-kafka-connect-couchbase#22]
In the current implementation, we don't return an error while creating a new connector [^1]. If we fail to create dcp client [^2] we can return error. 

In the current implementation, we don't return an error while creating a new producer [^3]. If we fail to create a producer we can return error. 

[^1]: https://github.com/Trendyol/go-kafka-connect-couchbase/blob/master/connector.go#L80
[^2]: https://github.com/Trendyol/go-kafka-connect-couchbase/blob/master/connector.go#L90
[^3]: https://github.com/Trendyol/go-kafka-connect-couchbase/blob/master/kafka/producer/producer.go#L29

**Comment by halilkocaoz** [comment]
should we do anything if err is not null at https://github.com/halilkocaoz/go-kafka-connect-couchbase/blob/22/example/main.go#L15

**Comment by oguzyildirim** [comment]
> should we do anything if err is not null at https://github.com/halilkocaoz/go-kafka-connect-couchbase/blob/22/example/main.go#L15

Sure, We'd be happy to show an example of how we can use it. You can panic if err is not nil.
