### ISSUE TITLE
fatal concurrency error at startup time

### ISSUE THREAD

**Issue by Du-Li** [Trendyol/go-kafka-connect-couchbase#32]
**Describe the bug**
When starting the go-kafka-connect-couchbase connector, sometimes there was an error right after the stream and dcp stream started messages: "fatal error: concurrent map iteration and map write". It looks like a race condition when registering the metric middleware on path /metrics and starting the api.

**To Reproduce**
1. extend the example main.go to print the received cb-dcp events
2. copy the example main.go and config.yml to an ubuntu box
3. run the code like `go run main.go`

{"level":"debug","time":"2023-03-21T04:39:33Z","message":"vbucket discovery opened with membership type: static"}
{"level":"debug","time":"2023-03-18T01:00:41Z","message":"ready to stream member number: 1, vBuckets range: 0-1023"}
{"level":"debug","time":"2023-03-18T01:00:42Z","message":"loaded checkpoint"}
{"level":"debug","time":"2023-03-18T01:00:42Z","message":"stream started"}
{"level":"debug","time":"2023-03-18T01:00:42Z","message":"started checkpoint schedule"}
{"level":"info","time":"2023-03-18T01:00:42Z","message":"dcp stream started"}
fatal error: concurrent map iteration and map write

goroutine 405 [running]:
github.com/Trendyol/go-dcp-client.(*metricCollector).Collect(0xc0206e27e0, 0x1759d4a?)
        /go/pkg/mod/github.com/!trendyol/go-dcp-client@v0.0.18/metric.go:45 +0x11e
github.com/prometheus/client_golang/prometheus.DescribeByCollect.func1()
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/collector.go:90 +0x2b
created by github.com/prometheus/client_golang/prometheus.DescribeByCollect
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/collector.go:89 +0x9c

**Expected behavior**
It's expected to continuously print the cb dcp events as long as a workload is fed into cb.

**Screenshots**
N/A

**Version (please complete the following information):**
 - OS: Linux ubuntu-box 5.4.231-137.341.amzn2.x86_64
 - Golang version: go1.18.1 linux/amd64
 - Couchbase: Community Edition 6.5.0 build 4966
 - Kafka: 3.3.1

**Additional context**

**Comment by mhmtszr** [comment]
Hello @Du-Li, which version of go-kafka-connect-couchbase have you used? Could you try it with the latest version v0.0.20?

**Comment by erayarslan** [comment]
Hi @Du-Li
this problem will be covered with next version.
thank you so much for contribution.

**Comment by Du-Li** [comment]
@erayarslan Yes this bug is gone in v0.0.21. Thanks!
