### ISSUE TITLE
keep state info on kafka 

### ISSUE THREAD

**Issue by Du-Li** [Trendyol/go-kafka-connect-couchbase#35]
**Is your feature request related to a problem? Please describe.**
Currently the dcp-kafka connector writes the state info (checkpoints) back to couchbase, which consequently magnifies the workload on CB. In my tests, for example, I generated 4k RPS to CB but observed 15k RPS there, which adds almost 3x extra workload to CB. This may not be acceptable in production. Moreover, conceptually, CDC is meant to be non-intrusive to the source databases. Keeping the state info on CB would cause many problems not only in terms of capacity but also breaking that read-only promise or expectation. 

**Describe the solution you'd like**
At least make it an option for the dcp-kafka connector to keep the state info on Kafka instead of CB.

**Describe alternatives you've considered**
Define an interface so the developer can choose to use Kafka or CB. The two paths will implement the same interface.

**Additional context**
In my use case, we are definitely not allowed to write to the CB cluster. CDC is meant to be read-only.

**Comment by Du-Li** [comment]
@erayarslan What's your team's opinion regarding this issue?

**Comment by Du-Li** [comment]
How about implementing an optional checkpointing mechanism that saves to kafka?

**Comment by erayarslan** [comment]
we already have abstraction on metadata in [here](https://github.com/Trendyol/go-dcp-client/blob/master/metadata.go)
currently we have filesystem and couchbase. default is couchbase.
i think kafka metadata implementation is a good idea on kafka connector project.
atleast we can give freedom about that.

**Comment by Du-Li** [comment]
The other Couchbase connector ([kafka-connect-couchbase](https://github.com/couchbase/kafka-connect-couchbase)) keeps state info in Kafka. I started from there but found its performance unsatisfactory. So I reimplemented a CB connector using your libraries. The e2e latencies improved 20x right away to the 100ms level. It would be ideal if you also implemented the kafka metadata option. Otherwise my project couldn't go to production. As said above, CDC is meant to be read-only so not allowed to write into the source database.

**Comment by erayarslan** [comment]
yes we are aware of java connector's behaviour. but another hand elasticsearch connector storing checkpoints on couchbase.
i think approaches differ here. but we are okay with kafka metadata feature.
thank you for feedback, we will implement this soon.

**Comment by Du-Li** [comment]
Thanks for your support. What timeline shall we expect?

**Comment by erayarslan** [comment]
hi @Du-Li 
with go-kafka-connect-couchbase v0.0.25, you can use kafka metadata feature.
our [example](https://github.com/Trendyol/go-kafka-connect-couchbase/blob/master/example/config.yml) updated with that.

thanks for idea, i hope it solve your requirements.

**Comment by Du-Li** [comment]
Awesome. Very impressed. Thank you. I will try it out and let you know.

**Comment by Du-Li** [comment]
@erayarslan I have tested the kafka metadata feature. It worked perfectly. Thank you!

However, after I restarted the dcp-kafka connector pods (k8s statefulset membeship) on the fly, the connectors were not able to resume from where they stopped, while their cpus stayed at 100% utilization. My checkpoint type was `manual`. Do you know what might caused this problem and how to fix it?

**Comment by erayarslan** [comment]
@Du-Li  thank you for testing kafka metadata. i am so glad it worked for you.
i tried your configuration on our kubernetes but cannot reproduce cpu utilization.
maybe you can upgrade latest version of go-kafka-connect-couchbase, which is currently v0.0.35.
we made some improvements on restoring streams, rollback etc.

or maybe u can share latest logs of connector, so we can diagnose

**Comment by Du-Li** [comment]
The version I tested was already v0.0.35. The logs were not meaningful. All the connectors just stopped there after printing the initialization messages such as dcp stream connected. They kept spinning the cpus 100% without doing anything visible.

**Comment by Du-Li** [comment]
In general, what settings are available for `checkpoint` and what differences they make? I cannot tell from your README.

**Comment by erayarslan** [comment]
only manual and auto options available for checkpoint. i think its not about checkpoint.
how much item produced your kafka metadata offset topic? can you tell?
because when you boot your application, kafka metadata feature consume whole offset topic to understand where you finished last stream.

**Comment by Du-Li** [comment]
gotcha!

When taking the cb metadata option, I noticed that the metadata topic data rate was like 12k RPS, as I noted above. Guess the kafka metadata option has a similar data rate.

I was running 10 dcp-kafka connector pods. When they are restarted, each of them might be all reading from the metadata topic, which is huge. That's perhaps why they all hang there using 100% cpu.

If my guess were right, some optimization would be required. Pod restarts are unavoidable in k8s for all kinds of reasons. The system wouldn't be useful if restart makes the pod hang.

**Comment by erayarslan** [comment]
because of this we are using compacted topic for offsets. also debezium, kafka using same system like that.
so kafka metadata okey but i think you need to tune .commit() frequency which is depend our kafka batch consumer configuration.

you can tune with these configs:
```
kafka.producerBatchSize
kafka.producerBatchTickerDuration
```

on the other hand i want to improve our offset consuming logic.
%100 cpu utilization its not good.

**Comment by Du-Li** [comment]
My settings were like
> kafka.producerBatchSize=50
> kafka.producerBatchTickerDuration=50ms

**Comment by erayarslan** [comment]
producerBatchTickerDuration means, connector will flush messages every 50ms and commit offsets.
producerBatchSize means when your messages in batch producer queue over producerBatchSize before 50ms trigger, connector will flush messages and commits offsets.

project still under development and not stable so i think its documentation issue.
we need to improve our documentation. :/

so in your case we need to increase these.
but size and tickerDuration config not enough.
i think we need to implement max bytes kinda config to avoid oom for big batches.

currently u need to set these by your avarage per message size.

maybe
`
kafka.producerBatchSize=100
kafka.producerBatchTickerDuration=10s
`

meanwhile, we will make the improvements i mentioned above.

**Comment by erayarslan** [comment]
TIL; in kafka connect couchbase default `kafka.producerBatchSize` is `2000` [here](https://github.com/couchbase/kafka-connect-couchbase/blob/master/src/main/java/com/couchbase/connect/kafka/config/source/SourceBehaviorConfig.java#L120)

**Comment by Du-Li** [comment]
@erayarslan Thanks for your explanations. Actually I tried different values in load testings but they didn't seem to make any difference.

**Comment by erayarslan** [comment]
@Du-Li did you clean the old metadata topic? or give different topic name to create new one?

**Comment by Du-Li** [comment]
I reused the old metadata topic without cleaning.

**Comment by erayarslan** [comment]
Kafka metadata always consume whole topic at the start of application.
We talked about how to keep the topic smaller above.

**Comment by erayarslan** [comment]
@Du-Li with v0.0.36 we descrease `segment.bytes` of metadata topic for increase compaction count.
can you upgrade and remove old metadata topic? let application create new metadata topic.

**Comment by Du-Li** [comment]
I have tested the new version. It worked fine although I haven't measured how much difference it makes. Thank you!

**Comment by erayarslan** [comment]
many thanks for your contributions!

**Comment by Du-Li** [comment]
@erayarslan Can you help estimate the size of checkpoint messages in kafka? Suppose there are avg 1000 CB DCP events per second and each event has three copies in the kafka. What's the size of each checkpoint message and how much storage space would be needed?

**Comment by Du-Li** [comment]
I need to capacity estimates for my kafka cluster. Can you give me a rough idea how much space (msg size and data rate) the checkpoint topic will need? It doesn't have to be too accurate. Thanks. @erayarslan

**Comment by erayarslan** [comment]
i saw compaction trigger when metadata topic size 3-5mb~ in my test cluster.
but this is not a guarantee. i think 100mb safe for kafka metadata topic.

**Comment by erayarslan** [comment]
for data rate its depend your batch size.
i think you can calculate like;
```checkpoint per second to kafka metadata = **event per second / batchSize * 1024**`
1024 is affected vbucket. i assumed they were all affected.
