### ISSUE TITLE
Add source timestamp to couchbase.Event

### ISSUE THREAD

**Issue by Du-Li** [Trendyol/go-kafka-connect-couchbase#38]
**Is your feature request related to a problem? Please describe.**
When using the cb-dcp-kafka connector to build a CDC data pipeline, we need to study metrics such as latencies in each component to perform the right optimizations. Currently, the `couchbase.Event` passed to `mapper` only has key, value and type. As a result, we cannot calculate the time spent between when an event occurs in CB and when the event is captured/processed by the connector.

**Describe the solution you'd like**
The DCP logs should have the information such as when an event is logged or persisted in the CB database. It would be very convenient if you could expose a timestamp like `EventTime` in `couchbase.Event`. Then we could easily calculate the latencies between CB and connector.

**Describe alternatives you've considered**
In absence of such a timestamp, we have to add one into the CB documents when a doc is created. However, such a timestamp may not be a natural part in the application data model. Moreover, it is when the doc is created in the application, not when it is persisted in the database. This is inaccurate and intrusive.

**Additional context**
The java-base CB connector does not expose this timestamp. The Debezium db source connectors in general expose two timestamps, `source.ts_ms` and `ts_ms`. Kafka consumer SDKs also expose the timestamp when an event is persisted in Kafka. Those timestamps are very useful for investigating latencies and optimizations.

**Comment by oguzyildirim** [comment]
Hello @Du-Li, that would be a good feature as far as I know we can get timestamps from CAS value but Couchbase Server should be 7.0 or later. We can add it as a feature maybe any ideas? @erayarslan @mhmtszr

**Comment by Du-Li** [comment]
That's awesome. Thanks for your quick attention.

It's a bit disappointing though that this timestamp is only available in CB 7.0 or above. Our current production is still using CB 6.5 and we won't be able to upgrade it in a short term. Is there some way to make it work for CB 6.5?

**Comment by erayarslan** [comment]
i checked version 6.5 of the couchbase. there doesn't seem to be a problem with this cas to eventTime conversion.

**Comment by erayarslan** [comment]
we implemented in `v0.0.37`
now you can use with `event.EventTime`

thank you so much for contribution💯

**Comment by Du-Li** [comment]
@erayarslan Thank you for implementing it. I have tested it. However, there was a big gap between this CAS-based timestamp (t2) and the timestamp (t1) I added into the doc when it was generated, actually t2 < t1 by up to a second. 

Do you know how CAS was created? What's the physical meaning? I was wondering if it could be rightly used as the timestamp a doc is persisted on CB.

**Comment by erayarslan** [comment]
@Du-Li i think its mean "event happen time in couchbase"
so when document create in couchbase, this mutation cas is create time.
or document deleted in couchbase, deletion cas time is delete time.

so when you start consuming for the first time, it is normal to see this gap.
after initial load its done, you will get new fresh events. gap gonna normal.

@oguzyildirim also has idea about DcpTime kinda field to set time(now) when our library consume event.

**Comment by oguzyildirim** [comment]
There is only one edge case about CAS as far as I know. if conflict resolution is to take an older document from the backup. 

I've added dcp latency but not tested yet.
