### ISSUE TITLE
Check whether given topic exists on given broker

### ISSUE THREAD

**Issue by ghost** [Trendyol/go-kafka-connect-couchbase#9]
The problem is that validation is needed to check whether a given topic exists on a specific broker. Currently, there is no way to determine if a topic exists on a broker, and this validation will be necessary for certain functionality in the application.

We can add validation when we are creating producer in producer.go

There are several go libraries that get all available topics since we use Kafka-go there is a way to do it https://github.com/segmentio/kafka-go#to-list-topics

**Comment by Oguzyildirim** [comment]
There are several go libraries that get all available topics since we use Kafka-go there is a way to do it  https://github.com/segmentio/kafka-go#to-list-topics

**Comment by erayarslan** [comment]
solved with https://github.com/Trendyol/go-kafka-connect-couchbase/commit/50cbc86e4c04e5694723ed8b2d82e4543152a34c
